source 'https://rubygems.org'

gem 'jekyll', '~> 4.3.3'

# Ruby 3.4 stdlib unbundled: add these
gem 'csv'
gem 'logger'
gem 'base64'
gem 'bigdecimal'
gem 'date'
gem 'ostruct'
gem 'stringio'
gem 'forwardable'
gem 'webrick'
gem 'jekyll-sitemap'

# Optional Windows optimization
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
